# Generated by Django 2.1.1 on 2018-09-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='ip',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
